### ISSUE TITLE
remove the latex compilation output from the log file bluelatex.out

### ISSUE THREAD

**Issue by monperrus** [gnieh/bluelatex#228] opened 2015-05-14 07:50 UTC
Hi all, 

I propose to remove remove the latex compilation outputs from the log file bluelatex.out.

--Martin

**Comment by satabin** [comment] 2015-05-14 08:43
duplicate of #199 ?

**Comment by monperrus** [comment] 2015-05-14 10:39
yes :-)

**Closed** 2015-05-15 15:17 UTC
Labels: duplicate
